main: me.cluter.fruittrees.Main
name: FruitBushes
version: 1.5
author: cluter123
depend: [cluterLib, FarmLifeAPI]

commands:
  sbush:
    description: Spawn a bush!
permissions:
  fruitbushes.spawn:
    description: Allows you to spawn a bush.